name: Push to Testflight

on:
  push:
    branches:
      - fastlane
      - development

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Switch to Xcode 11
      run: sudo xcode-select --switch /Applications/Xcode_11.app
    - name: Build
      run: |
        ls
        cd Emitron
        bundle install
        bundle exec fastlane -v
        bundle exec fastlane beta
